import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import QRCode from "react-qr-code";

const Userlist = [{ email: "1", password: "1" }];

export default function Home() {
  useEffect(() => {
    setloading(true);
    const email = sessionStorage.getItem("email");
    const password = sessionStorage.getItem("password");
    let flag = 0;
    if (email && password) {
      Userlist.forEach((a) => {
        if (a.email == email && a.password == password) {
          flag = 1;
        }
      });
      if (flag == 1) {
        setUserActive(1);
      }
    }
    setloading(false);
  }, []);

  const [loading, setloading] = useState(true);
  const [userActive, setUserActive] = useState(0);
  const [Product, setProduct] = useState({
    code: "",
    name: "",
    pack_date: "",
    trans_date: "",
    exp_date: "",
  });

  const Users = () => {
    const email = document.getElementById("email");
    const password = document.getElementById("password");
    let flag = 0;
    Userlist.forEach((a) => {
      if (a.email == email.value && a.password == password.value) {
        flag = 1;
      }
    });
    if (flag == 1) {
      sessionStorage.setItem("email", email.value);
      sessionStorage.setItem("password", password.value);
      setUserActive((a) => a + 1);
    } else {
      alert("Please Enter a Valied user details");
    }
  };
  return (
    <>
      <Head>
        <title>Fruits Scanner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="container">
        {loading ? (
          "loading...."
        ) : (
          <>
            {userActive == 0 && <PageLogin Users={Users} />}
            {userActive == 1 && (
              <EnterCode
                setProduct={setProduct}
                setUserActive={setUserActive}
              />
            )}
            {userActive == 2 && (
              <EnterProductDetails
                setProduct={setProduct}
                setUserActive={setUserActive}
              />
            )}
            {userActive == 3 && <QRGEN Product={Product} />}
          </>
        )}
      </div>
    </>
  );
}

const PageLogin = (props) => {
  return (
    <div className="forms">
      <div className="form-content">
        <div className="login-form">
          <div className="logo-img">
            <img src="Logo.png" />
          </div>
          <div className="title">Login</div>
          <form>
            <div className="input-boxes">
              <div className="input-box">
                <i className="fas fa-envelope"></i>
                <input
                  type="text"
                  id="email"
                  placeholder="Enter your email"
                  required
                />
              </div>
              <div className="input-box">
                <i className="fas fa-lock"></i>
                <input
                  type="password"
                  placeholder="Enter your password"
                  required
                  id="password"
                />
              </div>
              <div className="button input-box">
                <input type="button" onClick={props.Users} value="Sumbit" />
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

const EnterCode = (props) => {
  return (
    <div className="forms">
      <div className="form-content">
        <div className="login-form">
          <div className="logo-img">
            <img src="Logo.png" />
          </div>
          <div className="title">Fruit code</div>
          <form>
            <div className="input-boxes">
              <div className="input-box">
                <i className="bi bi-upc"></i>
                <input
                  type="text"
                  id="code"
                  placeholder="Enter fruit code"
                  required
                />
              </div>
              <div className="button input-box">
                <input
                  type="button"
                  onClick={() => {
                    if (document.getElementById("code").value) {
                      props.setProduct((a) => ({
                        ...a,
                        code: document.getElementById("code").value,
                      }));
                      props.setUserActive((a) => (a += 1));
                    }
                  }}
                  value="Next"
                />
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

const EnterProductDetails = (props) => {
  return (
    <div className="forms">
      <div className="form-content">
        <div className="login-form">
          <div className="logo-img">
            <img src="Logo.png" />
          </div>
          <div className="title">Fruit Details</div>
          <form>
            <div className="input-boxes">
              <div className="input-box">
                <i className="bi bi-card-heading"></i>
                <input
                  type="text"
                  id="name"
                  placeholder="Enter fruit name"
                  required
                />
              </div>
              <div className="input-box">
                <i className="bi bi-box-fill"></i>
                <input type="date" id="pdate" title="packing date" required />
              </div>
              <div className="input-box">
                <i className="bi bi-bus-front-fill"></i>
                <input type="date" id="tdate" title="transport date" required />
              </div>
              <div className="input-box">
                <i className="bi bi-explicit-fill"></i>
                <input type="date" id="edate" title="expery date" required />
              </div>
              <div className="button input-box">
                <input
                  type="button"
                  onClick={() => {
                    if (
                      document.getElementById("name").value &&
                      document.getElementById("pdate").value &&
                      document.getElementById("tdate").value &&
                      document.getElementById("edate").value
                    ) {
                      props.setProduct((a) => ({
                        ...a,
                        name: document.getElementById("name").value,
                        pack_date: document.getElementById("pdate").value,
                        trans_date: document.getElementById("tdate").value,
                        exp_date: document.getElementById("edate").value,
                      }));
                      props.setUserActive((a) => (a += 1));
                    }
                  }}
                  value="Next"
                />
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

const QRGEN = (props) => {
  let { code, name, pack_date, trans_date, exp_date } = props.Product;
  return (
    <div className="qr">
      <h2>
        QR-CODE has been successfully generated for{" "}
        <span>
          <i>{props.Product.name}</i>
        </span>
      </h2>
      <QRCode
        value={`https://fruitscanner.netlify.app/fruit?code=${code}&name=${name}&pdate=${pack_date}&tdate=${trans_date}&edate=${exp_date}`}
      />
      <span>scan the QR-CODE to view the details about the fruit</span>
    </div>
  );
};
